stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - vj_first
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  tags:
    - vj_first
  script:
    - echo "Deploying to production..."
    - npm run
 