stages:
  - build
  - test
  - deploy

variables:
  CI_DEBUG_TRACE: "true"
  REACT_APP_ENV: production

before_script:
  - npm install

build:
  stage: build
  tags:
    - vj_first
  script:
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  tags:
    - vj_first
  script:
    - npm test

deploy:
  stage: deploy
  tags:
    - vj_first
  script:
    - # Add your deployment commands here
      echo "Deploying to production"
  only:
    - main
