stages:
  - build
  - deploy

variables:
  NODE_IMAGE: node:latest

before_script:
  - npm install -g npm
  - npm install

build:
  stage: build
  tags:
    - vj_first
  script:
    - npm test
    - npm run build
  artifacts:
    path:
      bulds/
deploy:
  stage: deploy
  tags:
    - vj_first
  script:
    - echo "Deploying to production..."
    - npm run
 