stages:
  - build
  - deploy

variables:
  NODE_IMAGE: node:latest

before_script:
  - npm install -g npm

build:
  stage: build
  tags:
    - vj_first
  script:
    - npm install
    - npm test
    - npm run build
  artifacts:
    paths:
      - node_modules
      - bulds

deploy:
  stage: deploy
  tags:
    - vj_first
  script:
    - echo "Deploying to production..."
    - npm run
 